/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideLegalMedicalOutreachRouteImport } from './routes/guide.legal-medical-outreach'
import { Route as ApiPublicHooksTendersTickRouteImport } from './routes/api/public/hooks/tenders-tick'
import { Route as ApiPublicHooksSearchTickRouteImport } from './routes/api/public/hooks/search-tick'
import { Route as ApiPublicHooksGmapsTickRouteImport } from './routes/api/public/hooks/gmaps-tick'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideLegalMedicalOutreachRoute =
  GuideLegalMedicalOutreachRouteImport.update({
    id: '/guide/legal-medical-outreach',
    path: '/guide/legal-medical-outreach',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTendersTickRoute =
  ApiPublicHooksTendersTickRouteImport.update({
    id: '/api/public/hooks/tenders-tick',
    path: '/api/public/hooks/tenders-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSearchTickRoute =
  ApiPublicHooksSearchTickRouteImport.update({
    id: '/api/public/hooks/search-tick',
    path: '/api/public/hooks/search-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGmapsTickRoute = ApiPublicHooksGmapsTickRouteImport.update({
  id: '/api/public/hooks/gmaps-tick',
  path: '/api/public/hooks/gmaps-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guide/legal-medical-outreach': typeof GuideLegalMedicalOutreachRoute
  '/api/public/hooks/gmaps-tick': typeof ApiPublicHooksGmapsTickRoute
  '/api/public/hooks/search-tick': typeof ApiPublicHooksSearchTickRoute
  '/api/public/hooks/tenders-tick': typeof ApiPublicHooksTendersTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guide/legal-medical-outreach': typeof GuideLegalMedicalOutreachRoute
  '/api/public/hooks/gmaps-tick': typeof ApiPublicHooksGmapsTickRoute
  '/api/public/hooks/search-tick': typeof ApiPublicHooksSearchTickRoute
  '/api/public/hooks/tenders-tick': typeof ApiPublicHooksTendersTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guide/legal-medical-outreach': typeof GuideLegalMedicalOutreachRoute
  '/api/public/hooks/gmaps-tick': typeof ApiPublicHooksGmapsTickRoute
  '/api/public/hooks/search-tick': typeof ApiPublicHooksSearchTickRoute
  '/api/public/hooks/tenders-tick': typeof ApiPublicHooksTendersTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/guide/legal-medical-outreach'
    | '/api/public/hooks/gmaps-tick'
    | '/api/public/hooks/search-tick'
    | '/api/public/hooks/tenders-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/guide/legal-medical-outreach'
    | '/api/public/hooks/gmaps-tick'
    | '/api/public/hooks/search-tick'
    | '/api/public/hooks/tenders-tick'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/guide/legal-medical-outreach'
    | '/api/public/hooks/gmaps-tick'
    | '/api/public/hooks/search-tick'
    | '/api/public/hooks/tenders-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GuideLegalMedicalOutreachRoute: typeof GuideLegalMedicalOutreachRoute
  ApiPublicHooksGmapsTickRoute: typeof ApiPublicHooksGmapsTickRoute
  ApiPublicHooksSearchTickRoute: typeof ApiPublicHooksSearchTickRoute
  ApiPublicHooksTendersTickRoute: typeof ApiPublicHooksTendersTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/legal-medical-outreach': {
      id: '/guide/legal-medical-outreach'
      path: '/guide/legal-medical-outreach'
      fullPath: '/guide/legal-medical-outreach'
      preLoaderRoute: typeof GuideLegalMedicalOutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tenders-tick': {
      id: '/api/public/hooks/tenders-tick'
      path: '/api/public/hooks/tenders-tick'
      fullPath: '/api/public/hooks/tenders-tick'
      preLoaderRoute: typeof ApiPublicHooksTendersTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/search-tick': {
      id: '/api/public/hooks/search-tick'
      path: '/api/public/hooks/search-tick'
      fullPath: '/api/public/hooks/search-tick'
      preLoaderRoute: typeof ApiPublicHooksSearchTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/gmaps-tick': {
      id: '/api/public/hooks/gmaps-tick'
      path: '/api/public/hooks/gmaps-tick'
      fullPath: '/api/public/hooks/gmaps-tick'
      preLoaderRoute: typeof ApiPublicHooksGmapsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GuideLegalMedicalOutreachRoute: GuideLegalMedicalOutreachRoute,
  ApiPublicHooksGmapsTickRoute: ApiPublicHooksGmapsTickRoute,
  ApiPublicHooksSearchTickRoute: ApiPublicHooksSearchTickRoute,
  ApiPublicHooksTendersTickRoute: ApiPublicHooksTendersTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
