/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksTendersTickRouteImport } from './routes/api/public/hooks/tenders-tick'
import { Route as ApiPublicHooksSearchTickRouteImport } from './routes/api/public/hooks/search-tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTendersTickRoute =
  ApiPublicHooksTendersTickRouteImport.update({
    id: '/api/public/hooks/tenders-tick',
    path: '/api/public/hooks/tenders-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSearchTickRoute =
  ApiPublicHooksSearchTickRouteImport.update({
    id: '/api/public/hooks/search-tick',
    path: '/api/public/hooks/search-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/hooks/search-tick': typeof ApiPublicHooksSearchTickRoute
  '/api/public/hooks/tenders-tick': typeof ApiPublicHooksTendersTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/hooks/search-tick': typeof ApiPublicHooksSearchTickRoute
  '/api/public/hooks/tenders-tick': typeof ApiPublicHooksTendersTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/hooks/search-tick': typeof ApiPublicHooksSearchTickRoute
  '/api/public/hooks/tenders-tick': typeof ApiPublicHooksTendersTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/hooks/search-tick'
    | '/api/public/hooks/tenders-tick'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/hooks/search-tick' | '/api/public/hooks/tenders-tick'
  id:
    | '__root__'
    | '/'
    | '/api/public/hooks/search-tick'
    | '/api/public/hooks/tenders-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicHooksSearchTickRoute: typeof ApiPublicHooksSearchTickRoute
  ApiPublicHooksTendersTickRoute: typeof ApiPublicHooksTendersTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tenders-tick': {
      id: '/api/public/hooks/tenders-tick'
      path: '/api/public/hooks/tenders-tick'
      fullPath: '/api/public/hooks/tenders-tick'
      preLoaderRoute: typeof ApiPublicHooksTendersTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/search-tick': {
      id: '/api/public/hooks/search-tick'
      path: '/api/public/hooks/search-tick'
      fullPath: '/api/public/hooks/search-tick'
      preLoaderRoute: typeof ApiPublicHooksSearchTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicHooksSearchTickRoute: ApiPublicHooksSearchTickRoute,
  ApiPublicHooksTendersTickRoute: ApiPublicHooksTendersTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
